# Tensorflow Fundamentals

In [74]:
import numpy as np

import tensorflow as tf

## tf.constant()

In [75]:
tensor_0d = tf.constant(np.random.randint(0, 10))
tensor_0d

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [76]:
tensor_1d = tf.constant(np.random.randint(0, 10, (5)))
tensor_1d

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([4, 6, 2, 5, 1])>

In [77]:
tensor_2d = tf.constant(np.random.randint(0, 10, (4, 5)))
tensor_2d

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[0, 9, 0, 1, 7],
       [7, 0, 1, 0, 9],
       [5, 1, 2, 6, 7],
       [9, 9, 4, 6, 9]])>

In [78]:
tensor_3d = tf.constant(np.random.randint(0, 10, (3, 4, 5)))
tensor_3d

<tf.Tensor: shape=(3, 4, 5), dtype=int32, numpy=
array([[[1, 4, 7, 3, 2],
        [3, 3, 4, 6, 4],
        [5, 5, 3, 3, 1],
        [4, 6, 3, 3, 9]],

       [[2, 0, 1, 9, 3],
        [9, 0, 4, 8, 8],
        [1, 0, 4, 4, 5],
        [1, 2, 4, 4, 2]],

       [[2, 5, 0, 1, 9],
        [9, 1, 4, 2, 3],
        [7, 9, 5, 5, 8],
        [4, 1, 9, 2, 0]]])>

In [79]:
tensor_4d = tf.constant(np.random.randint(0, 10, (2, 3, 4, 5)))
tensor_4d

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[5, 5, 4, 3, 0],
         [0, 1, 0, 9, 3],
         [3, 8, 0, 5, 8],
         [3, 8, 9, 5, 9]],

        [[5, 5, 1, 2, 7],
         [3, 3, 7, 7, 5],
         [5, 2, 3, 4, 9],
         [8, 5, 2, 5, 6]],

        [[1, 8, 8, 0, 8],
         [3, 3, 8, 4, 5],
         [3, 3, 5, 4, 6],
         [9, 9, 9, 4, 3]]],


       [[[2, 0, 3, 1, 7],
         [5, 4, 3, 4, 9],
         [2, 9, 3, 6, 9],
         [7, 4, 3, 7, 7]],

        [[4, 6, 5, 8, 1],
         [6, 1, 0, 8, 1],
         [2, 2, 2, 6, 7],
         [7, 4, 7, 9, 0]],

        [[1, 6, 7, 3, 1],
         [6, 6, 8, 1, 8],
         [4, 5, 6, 8, 4],
         [4, 6, 6, 0, 7]]]])>

## tf.cast()

In [80]:
cast_tensor_0d = tf.cast(tensor_0d, tf.bool)
cast_tensor_0d

<tf.Tensor: shape=(), dtype=bool, numpy=False>