# 1. Tensorflow Fundamentals

In [1]:
import numpy as np

import tensorflow as tf

## tf.constant()

In [2]:
tensor_0d = tf.constant(np.random.randint(0, 10))
print(tensor_0d)

tf.Tensor(2, shape=(), dtype=int32)


In [3]:
tensor_1d = tf.constant(np.random.randint(0, 10, (5)))
print(tensor_1d)

tf.Tensor([7 8 2 0 6], shape=(5,), dtype=int32)


In [4]:
tensor_2d = tf.constant(np.random.randint(0, 10, (4, 5)))
print(tensor_2d)

tf.Tensor(
[[9 9 6 5 0]
 [3 7 9 5 1]
 [5 1 2 0 4]
 [3 0 5 9 6]], shape=(4, 5), dtype=int32)


In [5]:
tensor_3d = tf.constant(np.random.randint(0, 10, (3, 4, 5)))
print(tensor_3d)

tf.Tensor(
[[[6 1 7 0 3]
  [8 1 9 0 4]
  [5 9 4 7 2]
  [3 6 7 3 2]]

 [[9 2 2 1 1]
  [2 3 6 6 6]
  [7 8 9 2 8]
  [8 5 8 7 3]]

 [[9 2 3 2 9]
  [0 8 1 2 2]
  [1 4 0 2 9]
  [0 9 4 3 6]]], shape=(3, 4, 5), dtype=int32)


In [6]:
tensor_4d = tf.constant(np.random.randint(0, 10, (2, 3, 4, 5)))
print(tensor_4d)

tf.Tensor(
[[[[9 1 7 9 3]
   [9 2 8 2 8]
   [2 1 5 1 9]
   [4 6 5 6 9]]

  [[6 8 7 0 6]
   [5 2 6 4 7]
   [9 1 9 1 7]
   [0 7 5 4 9]]

  [[1 2 4 7 1]
   [9 4 0 7 1]
   [9 5 3 1 6]
   [3 2 3 6 6]]]


 [[[3 4 0 2 4]
   [6 4 8 8 6]
   [0 1 4 5 8]
   [9 5 5 1 9]]

  [[8 4 6 7 0]
   [5 6 7 1 4]
   [2 6 7 9 8]
   [7 1 8 3 6]]

  [[8 7 2 8 0]
   [6 7 3 6 2]
   [1 5 9 3 6]
   [1 9 5 0 0]]]], shape=(2, 3, 4, 5), dtype=int32)


In [7]:
tensor_boolean_0d = tf.constant(True)
print(tensor_boolean_0d)

tf.Tensor(True, shape=(), dtype=bool)


In [8]:
tensor_boolean_1d = tf.constant([True, True, False])
print(tensor_boolean_1d)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [9]:
tensor_string_0d = tf.constant("Hello World")
print(tensor_string_0d)

tf.Tensor(b'Hello World', shape=(), dtype=string)


In [10]:
tensor_string_1d = tf.constant(["Hello", "World"])
print(tensor_string_1d)

tf.Tensor([b'Hello' b'World'], shape=(2,), dtype=string)


## tf.cast()

In [11]:
cast_tensor_3d = tf.cast(tensor_3d, dtype=tf.bool)
print(cast_tensor_3d)

tf.Tensor(
[[[ True  True  True False  True]
  [ True  True  True False  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [False  True  True  True  True]
  [ True  True False  True  True]
  [False  True  True  True  True]]], shape=(3, 4, 5), dtype=bool)


## tf.eye()

In [12]:
eye_tensor = tf.eye(num_rows=8, batch_shape=[2], dtype=tf.dtypes.int32)
print(eye_tensor)

tf.Tensor(
[[[1 0 0 0 0 0 0 0]
  [0 1 0 0 0 0 0 0]
  [0 0 1 0 0 0 0 0]
  [0 0 0 1 0 0 0 0]
  [0 0 0 0 1 0 0 0]
  [0 0 0 0 0 1 0 0]
  [0 0 0 0 0 0 1 0]
  [0 0 0 0 0 0 0 1]]

 [[1 0 0 0 0 0 0 0]
  [0 1 0 0 0 0 0 0]
  [0 0 1 0 0 0 0 0]
  [0 0 0 1 0 0 0 0]
  [0 0 0 0 1 0 0 0]
  [0 0 0 0 0 1 0 0]
  [0 0 0 0 0 0 1 0]
  [0 0 0 0 0 0 0 1]]], shape=(2, 8, 8), dtype=int32)


## tf.fill()

In [13]:
fill_tensor = tf.fill(dims=(2, 3, 4), value=8)
print(fill_tensor)

tf.Tensor(
[[[8 8 8 8]
  [8 8 8 8]
  [8 8 8 8]]

 [[8 8 8 8]
  [8 8 8 8]
  [8 8 8 8]]], shape=(2, 3, 4), dtype=int32)


## tf.ones()

In [14]:
ones_tensor = tf.ones(shape=(2, 3, 4), dtype=tf.dtypes.int32)
print(ones_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(2, 3, 4), dtype=int32)


## tf.ones_like()

In [15]:
ones_like_tensor = tf.ones_like(input=tensor_3d, dtype=tf.dtypes.int32)
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]], shape=(3, 4, 5), dtype=int32)


## tf.zeros()

In [16]:
zeros_tensor = tf.zeros(shape=(2, 3, 4), dtype=tf.dtypes.int32)
print(zeros_tensor)

tf.Tensor(
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]], shape=(2, 3, 4), dtype=int32)


## tf.zeros_like()

In [17]:
zeros_like_tensor = tf.zeros_like(input=tensor_3d, dtype=tf.dtypes.int32)
print(zeros_like_tensor)

tf.Tensor(
[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]], shape=(3, 4, 5), dtype=int32)


## tf.shape()

In [18]:
shape_tensor = tf.shape(input=tensor_3d)
print(shape_tensor)

tf.Tensor([3 4 5], shape=(3,), dtype=int32)


## tf.size()

In [19]:
size_tensor = tf.size(input=tensor_3d)
print(size_tensor)

tf.Tensor(60, shape=(), dtype=int32)


## tf.random.normal()

In [20]:
random_normal_tensor = tf.random.normal(
    shape=(3, 4, 5),
    mean=100,
    stddev=10,
    seed=42,
)
print(random_normal_tensor)

tf.Tensor(
[[[ 97.192245  98.62248   93.2367   100.245804  91.064156]
  [ 91.71527  112.06895  113.81016   85.442024  97.537865]
  [ 86.391594 110.8796    96.48834   94.861465 134.1172  ]
  [100.58855  108.91802   92.47117   95.66427  124.53853 ]]

 [[103.13744   94.72638  108.524994  94.620865 110.51236 ]
  [100.9101   100.407814 108.86037   93.40217  127.01756 ]
  [109.43287  101.415474  93.13509  106.20947  116.37643 ]
  [ 97.660736 111.947395  96.7598   107.910866  84.205414]]

 [[101.84361   96.77201   96.687164  92.506226  87.44516 ]
  [109.09204  100.34244  112.57801  121.37242   95.20366 ]
  [ 94.536316 105.34391   94.06689  111.86012  105.92192 ]
  [ 91.172615  97.20807  105.73751  103.22316   83.58027 ]]], shape=(3, 4, 5), dtype=float32)


## tf.random.uniform()

In [21]:
random_uniform_tensor = tf.random.uniform(
    shape=(3, 4, 5),
    minval=0,
    maxval=10,
    dtype=tf.dtypes.int32,
    seed=42,
)
print(random_uniform_tensor)

tf.Tensor(
[[[2 4 3 9 1]
  [8 8 3 5 6]
  [6 9 9 6 1]
  [7 5 2 2 0]]

 [[8 1 6 1 2]
  [3 9 0 2 9]
  [6 6 2 9 2]
  [5 2 8 6 2]]

 [[5 0 4 8 3]
  [9 8 5 5 8]
  [7 9 6 9 6]
  [6 4 9 6 1]]], shape=(3, 4, 5), dtype=int32)
