# 2. Tensor Indexing

In [25]:
import numpy as np

import tensorflow as tf

In [34]:
np.random.seed(42)

tensor = tf.constant(np.random.randint(0, 10, (3, 4, 5)))

print(tensor)

tf.Tensor(
[[[6 3 7 4 6]
  [9 2 6 7 4]
  [3 7 7 2 5]
  [4 1 7 5 1]]

 [[4 0 9 5 8]
  [0 9 2 6 3]
  [8 2 4 2 6]
  [4 8 6 1 3]]

 [[8 1 9 8 9]
  [4 1 3 6 7]
  [2 0 3 1 7]
  [3 1 5 5 9]]], shape=(3, 4, 5), dtype=int32)


In [36]:
print(tensor[1:2])
print(tensor[1:])
print(tensor[:2])

tf.Tensor(
[[[4 0 9 5 8]
  [0 9 2 6 3]
  [8 2 4 2 6]
  [4 8 6 1 3]]], shape=(1, 4, 5), dtype=int32)
tf.Tensor(
[[[4 0 9 5 8]
  [0 9 2 6 3]
  [8 2 4 2 6]
  [4 8 6 1 3]]

 [[8 1 9 8 9]
  [4 1 3 6 7]
  [2 0 3 1 7]
  [3 1 5 5 9]]], shape=(2, 4, 5), dtype=int32)
tf.Tensor(
[[[6 3 7 4 6]
  [9 2 6 7 4]
  [3 7 7 2 5]
  [4 1 7 5 1]]

 [[4 0 9 5 8]
  [0 9 2 6 3]
  [8 2 4 2 6]
  [4 8 6 1 3]]], shape=(2, 4, 5), dtype=int32)


In [37]:
print(tensor[1:2, 1:3])
print(tensor[1:2, 1:])
print(tensor[1:2, :3])

tf.Tensor(
[[[0 9 2 6 3]
  [8 2 4 2 6]]], shape=(1, 2, 5), dtype=int32)
tf.Tensor(
[[[0 9 2 6 3]
  [8 2 4 2 6]
  [4 8 6 1 3]]], shape=(1, 3, 5), dtype=int32)
tf.Tensor(
[[[4 0 9 5 8]
  [0 9 2 6 3]
  [8 2 4 2 6]]], shape=(1, 3, 5), dtype=int32)


In [39]:
print(tensor[1:2, 1:3, 1:4])
print(tensor[1:2, 1:3, 1:])
print(tensor[1:2, 1:3, :4])

tf.Tensor(
[[[9 2 6]
  [2 4 2]]], shape=(1, 2, 3), dtype=int32)
tf.Tensor(
[[[9 2 6 3]
  [2 4 2 6]]], shape=(1, 2, 4), dtype=int32)
tf.Tensor(
[[[0 9 2 6]
  [8 2 4 2]]], shape=(1, 2, 4), dtype=int32)
