# 3. Tensorflow Math

In [1]:
import numpy as np

import tensorflow as tf

In [32]:
tensor_normal = tf.random.normal((2, 3, 4))
tensor_1 = tf.constant(np.random.randint(0, 9, (2, 3, 4)))
tensor_2 = tf.constant(np.random.randint(0, 9, (2, 3, 4)))

print(tensor_normal)
print(tensor_1)
print(tensor_2)

tf.Tensor(
[[[ 1.773103   -1.2574004   0.16737376  1.7515436 ]
  [ 0.0255055   1.0920552  -0.8895668  -0.06589238]
  [-0.07758555 -1.658386    0.42244086  1.1226646 ]]

 [[-0.4027963   0.43229944  0.12593758 -0.19113998]
  [-0.02955609 -0.32555753 -1.3167534  -0.87642074]
  [ 1.5191953  -0.81137294 -0.18006086 -0.5017856 ]]], shape=(2, 3, 4), dtype=float32)
tf.Tensor(
[[[0 5 5 0]
  [4 6 6 6]
  [3 0 1 8]]

 [[5 8 6 2]
  [0 5 3 3]
  [7 8 5 3]]], shape=(2, 3, 4), dtype=int32)
tf.Tensor(
[[[5 3 7 0]
  [4 4 2 2]
  [6 5 3 7]]

 [[5 5 4 3]
  [5 7 1 7]
  [2 1 7 5]]], shape=(2, 3, 4), dtype=int32)


## tf.math.abs()

In [33]:
tensor_abs = tf.math.abs(tensor_normal)

print(tensor_abs)

tf.Tensor(
[[[1.773103   1.2574004  0.16737376 1.7515436 ]
  [0.0255055  1.0920552  0.8895668  0.06589238]
  [0.07758555 1.658386   0.42244086 1.1226646 ]]

 [[0.4027963  0.43229944 0.12593758 0.19113998]
  [0.02955609 0.32555753 1.3167534  0.87642074]
  [1.5191953  0.81137294 0.18006086 0.5017856 ]]], shape=(2, 3, 4), dtype=float32)


## add() / subtract() / multiply() / divide()

In [34]:
tensor_add = tf.math.add(tensor_1, tensor_2)
tensor_subtract = tf.math.subtract(tensor_1, tensor_2)
tensor_multiply = tf.math.multiply(tensor_1, tensor_2)
tensor_divide = tf.math.divide(tensor_1, tensor_2)
tensor_pow = tf.math.pow(tensor_1, tensor_2)

print(tensor_add)
print(tensor_subtract)
print(tensor_multiply)
print(tensor_divide)
print(tensor_pow)

tf.Tensor(
[[[ 5  8 12  0]
  [ 8 10  8  8]
  [ 9  5  4 15]]

 [[10 13 10  5]
  [ 5 12  4 10]
  [ 9  9 12  8]]], shape=(2, 3, 4), dtype=int32)
tf.Tensor(
[[[-5  2 -2  0]
  [ 0  2  4  4]
  [-3 -5 -2  1]]

 [[ 0  3  2 -1]
  [-5 -2  2 -4]
  [ 5  7 -2 -2]]], shape=(2, 3, 4), dtype=int32)
tf.Tensor(
[[[ 0 15 35  0]
  [16 24 12 12]
  [18  0  3 56]]

 [[25 40 24  6]
  [ 0 35  3 21]
  [14  8 35 15]]], shape=(2, 3, 4), dtype=int32)
tf.Tensor(
[[[0.         1.66666667 0.71428571        nan]
  [1.         1.5        3.         3.        ]
  [0.5        0.         0.33333333 1.14285714]]

 [[1.         1.6        1.5        0.66666667]
  [0.         0.71428571 3.         0.42857143]
  [3.5        8.         0.71428571 0.6       ]]], shape=(2, 3, 4), dtype=float64)
tf.Tensor(
[[[      0     125   78125       1]
  [    256    1296      36      36]
  [    729       0       1 2097152]]

 [[   3125   32768    1296       8]
  [      0   78125       3    2187]
  [     49       8   78125     243]]], shape=

## maximum() / minimum()

In [35]:
tensor_maximum = tf.math.maximum(tensor_1, tensor_2)
tensor_minimum = tf.math.minimum(tensor_1, tensor_2)

print(tensor_maximum)
print(tensor_minimum)

tf.Tensor(
[[[5 5 7 0]
  [4 6 6 6]
  [6 5 3 8]]

 [[5 8 6 3]
  [5 7 3 7]
  [7 8 7 5]]], shape=(2, 3, 4), dtype=int32)
tf.Tensor(
[[[0 3 5 0]
  [4 4 2 2]
  [3 0 1 7]]

 [[5 5 4 2]
  [0 5 1 3]
  [2 1 5 3]]], shape=(2, 3, 4), dtype=int32)


## argmax() / argmin()

In [38]:
tensor_argmax_axis0 = tf.math.argmax(tensor_1, axis=0)
tensor_argmax_axis1 = tf.math.argmax(tensor_1, axis=1)
tensor_argmax_axis2 = tf.math.argmax(tensor_1, axis=2)
tensor_argmin_axis0 = tf.math.argmin(tensor_1, axis=0)
tensor_argmin_axis1 = tf.math.argmin(tensor_1, axis=1)
tensor_argmin_axis2 = tf.math.argmin(tensor_1, axis=2)

print(tensor_argmax_axis0)
print(tensor_argmax_axis1)
print(tensor_argmax_axis2)
print(tensor_argmin_axis0)
print(tensor_argmin_axis1)
print(tensor_argmin_axis2)

tf.Tensor(
[[1 1 1 1]
 [0 0 0 0]
 [1 1 1 0]], shape=(3, 4), dtype=int64)
tf.Tensor(
[[1 1 1 2]
 [2 0 0 1]], shape=(2, 4), dtype=int64)
tf.Tensor(
[[1 1 3]
 [1 1 1]], shape=(2, 3), dtype=int64)
tf.Tensor(
[[0 0 0 0]
 [1 1 1 1]
 [0 0 0 1]], shape=(3, 4), dtype=int64)
tf.Tensor(
[[0 2 2 0]
 [1 1 1 0]], shape=(2, 4), dtype=int64)
tf.Tensor(
[[0 0 1]
 [3 0 3]], shape=(2, 3), dtype=int64)
