# 3. Tensorflow Math

In [34]:
import numpy as np

import tensorflow as tf

In [35]:
tf.random.set_seed(42)

In [36]:
tensor_normal = tf.random.normal((2, 3, 4))
tensor_1 = tf.constant(np.random.randint(0, 9, (2, 3, 4)), dtype=tf.dtypes.float32)
tensor_2 = tf.constant(np.random.randint(0, 9, (2, 3, 4)), dtype=tf.dtypes.float32)

print(tensor_normal)
print(tensor_1)
print(tensor_2)

tf.Tensor(
[[[ 0.3274685  -0.8426258   0.3194337  -1.4075519 ]
  [-2.3880599  -1.0392479  -0.5573232   0.539707  ]
  [ 1.6994323   0.28893656 -1.5066116  -0.26454744]]

 [[-0.59722406 -1.9171132  -0.62044144  0.8504023 ]
  [-0.40604794 -3.0258412   0.9058464   0.29855987]
  [-0.22561555 -0.7616443  -1.891714   -0.9384712 ]]], shape=(2, 3, 4), dtype=float32)
tf.Tensor(
[[[5. 5. 8. 2.]
  [0. 7. 8. 8.]
  [7. 7. 4. 6.]]

 [[5. 0. 1. 5.]
  [7. 1. 6. 1.]
  [8. 5. 2. 4.]]], shape=(2, 3, 4), dtype=float32)
tf.Tensor(
[[[3. 8. 6. 3.]
  [8. 6. 2. 4.]
  [2. 0. 2. 6.]]

 [[4. 7. 3. 8.]
  [2. 1. 1. 2.]
  [3. 6. 1. 2.]]], shape=(2, 3, 4), dtype=float32)


## abs()

In [37]:
tensor_abs = tf.math.abs(tensor_normal)

print(tensor_abs)

tf.Tensor(
[[[0.3274685  0.8426258  0.3194337  1.4075519 ]
  [2.3880599  1.0392479  0.5573232  0.539707  ]
  [1.6994323  0.28893656 1.5066116  0.26454744]]

 [[0.59722406 1.9171132  0.62044144 0.8504023 ]
  [0.40604794 3.0258412  0.9058464  0.29855987]
  [0.22561555 0.7616443  1.891714   0.9384712 ]]], shape=(2, 3, 4), dtype=float32)


## add() / subtract() / multiply() / divide()

In [38]:
tensor_add = tf.math.add(tensor_1, tensor_2)
tensor_subtract = tf.math.subtract(tensor_1, tensor_2)
tensor_multiply = tf.math.multiply(tensor_1, tensor_2)
tensor_divide = tf.math.divide(tensor_1, tensor_2)
tensor_pow = tf.math.pow(tensor_1, tensor_2)

print(tensor_add)
print(tensor_subtract)
print(tensor_multiply)
print(tensor_divide)
print(tensor_pow)

tf.Tensor(
[[[ 8. 13. 14.  5.]
  [ 8. 13. 10. 12.]
  [ 9.  7.  6. 12.]]

 [[ 9.  7.  4. 13.]
  [ 9.  2.  7.  3.]
  [11. 11.  3.  6.]]], shape=(2, 3, 4), dtype=float32)
tf.Tensor(
[[[ 2. -3.  2. -1.]
  [-8.  1.  6.  4.]
  [ 5.  7.  2.  0.]]

 [[ 1. -7. -2. -3.]
  [ 5.  0.  5. -1.]
  [ 5. -1.  1.  2.]]], shape=(2, 3, 4), dtype=float32)
tf.Tensor(
[[[15. 40. 48.  6.]
  [ 0. 42. 16. 32.]
  [14.  0.  8. 36.]]

 [[20.  0.  3. 40.]
  [14.  1.  6.  2.]
  [24. 30.  2.  8.]]], shape=(2, 3, 4), dtype=float32)
tf.Tensor(
[[[1.6666666  0.625      1.3333334  0.6666667 ]
  [0.         1.1666666  4.         2.        ]
  [3.5               inf 2.         1.        ]]

 [[1.25       0.         0.33333334 0.625     ]
  [3.5        1.         6.         0.5       ]
  [2.6666667  0.8333333  2.         2.        ]]], shape=(2, 3, 4), dtype=float32)
tf.Tensor(
[[[1.25000e+02 3.90625e+05 2.62144e+05 8.00000e+00]
  [0.00000e+00 1.17649e+05 6.40000e+01 4.09600e+03]
  [4.90000e+01 1.00000e+00 1.60000e+01 4.6656

## maximum() / minimum()

In [39]:
tensor_maximum = tf.math.maximum(tensor_1, tensor_2)
tensor_minimum = tf.math.minimum(tensor_1, tensor_2)

print(tensor_maximum)
print(tensor_minimum)

tf.Tensor(
[[[5. 8. 8. 3.]
  [8. 7. 8. 8.]
  [7. 7. 4. 6.]]

 [[5. 7. 3. 8.]
  [7. 1. 6. 2.]
  [8. 6. 2. 4.]]], shape=(2, 3, 4), dtype=float32)
tf.Tensor(
[[[3. 5. 6. 2.]
  [0. 6. 2. 4.]
  [2. 0. 2. 6.]]

 [[4. 0. 1. 5.]
  [2. 1. 1. 1.]
  [3. 5. 1. 2.]]], shape=(2, 3, 4), dtype=float32)


## argmax() / argmin()

In [40]:
tensor_argmax_axis0 = tf.math.argmax(tensor_1, axis=0)
tensor_argmax_axis1 = tf.math.argmax(tensor_1, axis=1)
tensor_argmax_axis2 = tf.math.argmax(tensor_1, axis=2)
tensor_argmin_axis0 = tf.math.argmin(tensor_1, axis=0)
tensor_argmin_axis1 = tf.math.argmin(tensor_1, axis=1)
tensor_argmin_axis2 = tf.math.argmin(tensor_1, axis=2)

print(tensor_argmax_axis0)
print(tensor_argmax_axis1)
print(tensor_argmax_axis2)
print(tensor_argmin_axis0)
print(tensor_argmin_axis1)
print(tensor_argmin_axis2)

tf.Tensor(
[[0 0 0 1]
 [1 0 0 0]
 [1 0 0 0]], shape=(3, 4), dtype=int64)
tf.Tensor(
[[2 1 0 1]
 [2 2 1 0]], shape=(2, 4), dtype=int64)
tf.Tensor(
[[2 2 0]
 [0 0 0]], shape=(2, 3), dtype=int64)
tf.Tensor(
[[0 1 1 0]
 [0 1 1 1]
 [0 1 1 1]], shape=(3, 4), dtype=int64)
tf.Tensor(
[[1 0 2 0]
 [0 0 0 1]], shape=(2, 4), dtype=int64)
tf.Tensor(
[[3 0 2]
 [1 1 2]], shape=(2, 3), dtype=int64)


## equal()

In [41]:
tensor_equal = tf.math.equal(tensor_1, tensor_2)

print(tensor_equal)

tf.Tensor(
[[[False False False False]
  [False False False False]
  [False False False  True]]

 [[False False False False]
  [False  True False False]
  [False False False False]]], shape=(2, 3, 4), dtype=bool)


## reduce_sum()

In [42]:
tensor_reduce_sum_axis0 = tf.math.reduce_sum(tensor_1, axis=0, keepdims=False)
tensor_reduce_sum_axis1 = tf.math.reduce_sum(tensor_1, axis=1, keepdims=False)
tensor_reduce_sum_axis2 = tf.math.reduce_sum(tensor_1, axis=2, keepdims=False)

print(tensor_reduce_sum_axis0)
print(tensor_reduce_sum_axis1)
print(tensor_reduce_sum_axis2)

tf.Tensor(
[[10.  5.  9.  7.]
 [ 7.  8. 14.  9.]
 [15. 12.  6. 10.]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[12. 19. 20. 16.]
 [20.  6.  9. 10.]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[20. 23. 24.]
 [11. 15. 19.]], shape=(2, 3), dtype=float32)


## reduce_mean()

In [43]:
tensor_reduce_mean_axis0 = tf.math.reduce_mean(tensor_1, axis=0, keepdims=False)
tensor_reduce_mean_axis1 = tf.math.reduce_mean(tensor_1, axis=1, keepdims=False)
tensor_reduce_mean_axis2 = tf.math.reduce_mean(tensor_1, axis=2, keepdims=False)

print(tensor_reduce_mean_axis0)
print(tensor_reduce_mean_axis1)
print(tensor_reduce_mean_axis2)

tf.Tensor(
[[5.  2.5 4.5 3.5]
 [3.5 4.  7.  4.5]
 [7.5 6.  3.  5. ]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[4.        6.3333335 6.6666665 5.3333335]
 [6.6666665 2.        3.        3.3333333]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[5.   5.75 6.  ]
 [2.75 3.75 4.75]], shape=(2, 3), dtype=float32)


## reduce_max() / reduce_min()

In [44]:
tensor_reduce_max_axis0 = tf.math.reduce_max(tensor_1, axis=0, keepdims=False)
tensor_reduce_max_axis1 = tf.math.reduce_max(tensor_1, axis=1, keepdims=False)
tensor_reduce_max_axis2 = tf.math.reduce_max(tensor_1, axis=2, keepdims=False)
tensor_reduce_min_axis0 = tf.math.reduce_min(tensor_1, axis=0, keepdims=False)
tensor_reduce_min_axis1 = tf.math.reduce_min(tensor_1, axis=1, keepdims=False)
tensor_reduce_min_axis2 = tf.math.reduce_min(tensor_1, axis=2, keepdims=False)

print(tensor_reduce_max_axis0)
print(tensor_reduce_max_axis1)
print(tensor_reduce_max_axis2)
print(tensor_reduce_min_axis0)
print(tensor_reduce_min_axis1)
print(tensor_reduce_min_axis2)

tf.Tensor(
[[5. 5. 8. 5.]
 [7. 7. 8. 8.]
 [8. 7. 4. 6.]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[7. 7. 8. 8.]
 [8. 5. 6. 5.]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[8. 8. 7.]
 [5. 7. 8.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[5. 0. 1. 2.]
 [0. 1. 6. 1.]
 [7. 5. 2. 4.]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[0. 5. 4. 2.]
 [5. 0. 1. 1.]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[2. 0. 4.]
 [0. 1. 2.]], shape=(2, 3), dtype=float32)


## sigmoid()

In [45]:
tensor_sigmoid = tf.math.sigmoid(tensor_1)

print(tensor_sigmoid)

tf.Tensor(
[[[0.9933072  0.9933072  0.99966466 0.8807971 ]
  [0.5        0.99908894 0.99966466 0.99966466]
  [0.99908894 0.99908894 0.98201376 0.99752736]]

 [[0.9933072  0.5        0.7310586  0.9933072 ]
  [0.99908894 0.7310586  0.99752736 0.7310586 ]
  [0.99966466 0.9933072  0.8807971  0.98201376]]], shape=(2, 3, 4), dtype=float32)


## top_k()

In [48]:
tensor_top_k = tf.math.top_k(tensor_1, k=2)

print(tensor_top_k)

TopKV2(values=<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[8., 5., 5.],
        [8., 8., 7.],
        [7., 7., 6.]],

       [[5., 5., 1.],
        [7., 6., 1.],
        [8., 5., 4.]]], dtype=float32)>, indices=<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[2, 0, 1],
        [2, 3, 1],
        [0, 1, 3]],

       [[0, 3, 2],
        [0, 2, 1],
        [0, 1, 3]]])>)
