# 4. Tensorflow Linear Algebra


In [2]:
import numpy as np

import tensorflow as tf

In [3]:
np.random.seed(42)
tf.random.set_seed(42)

In [4]:
tensor_1 = tf.constant(np.random.randint(1, 6, (2, 3, 4)), dtype=tf.dtypes.int32)
tensor_2 = tf.constant(np.random.randint(1, 6, (2, 4, 3)), dtype=tf.dtypes.int32)

print(tensor_1)
print(tensor_2)

tf.Tensor(
[[[4 5 3 5]
  [5 2 3 3]
  [3 5 4 3]]

 [[5 2 4 2]
  [4 5 1 4]
  [2 5 4 1]]], shape=(2, 3, 4), dtype=int32)
tf.Tensor(
[[[1 3 3]
  [2 4 4]
  [3 4 4]
  [1 3 5]]

 [[3 5 1]
  [2 4 1]
  [4 2 2]
  [1 2 5]]], shape=(2, 4, 3), dtype=int32)


## transpose()


In [5]:
tensor_1_transpose = tf.transpose(tensor_1)
tensor_2_transpose = tf.transpose(tensor_2)

print(tensor_1_transpose)
print(tensor_2_transpose)

tf.Tensor(
[[[4 5]
  [5 4]
  [3 2]]

 [[5 2]
  [2 5]
  [5 5]]

 [[3 4]
  [3 1]
  [4 4]]

 [[5 2]
  [3 4]
  [3 1]]], shape=(4, 3, 2), dtype=int32)
tf.Tensor(
[[[1 3]
  [2 2]
  [3 4]
  [1 1]]

 [[3 5]
  [4 4]
  [4 2]
  [3 2]]

 [[3 1]
  [4 1]
  [4 2]
  [5 5]]], shape=(3, 4, 2), dtype=int32)


## matmul()


In [6]:
tensor_matmul = tf.linalg.matmul(tensor_1, tensor_2)

print(tensor_matmul)

tf.Tensor(
[[[28 59 69]
  [21 44 50]
  [28 54 60]]

 [[37 45 25]
  [30 50 31]
  [33 40 20]]], shape=(2, 3, 3), dtype=int32)


## band_part()

In [7]:
tensor_matrix = tf.constant(np.random.randint(1, 6, (5, 5)), dtype=tf.dtypes.int32)
tensor_band_part_lower = tf.linalg.band_part(tensor_matrix, -1, 0)
tensor_band_part_upper = tf.linalg.band_part(tensor_matrix, 0, -1)
tensor_band_part_diagonal = tf.linalg.band_part(tensor_matrix, 0, 0)

print(tensor_matrix)
print(tensor_band_part_lower)
print(tensor_band_part_upper)
print(tensor_band_part_diagonal)

tf.Tensor(
[[2 4 4 4 4]
 [5 3 1 4 2]
 [4 2 2 4 5]
 [2 2 4 2 2]
 [4 4 1 5 5]], shape=(5, 5), dtype=int32)
tf.Tensor(
[[2 0 0 0 0]
 [5 3 0 0 0]
 [4 2 2 0 0]
 [2 2 4 2 0]
 [4 4 1 5 5]], shape=(5, 5), dtype=int32)
tf.Tensor(
[[2 4 4 4 4]
 [0 3 1 4 2]
 [0 0 2 4 5]
 [0 0 0 2 2]
 [0 0 0 0 5]], shape=(5, 5), dtype=int32)
tf.Tensor(
[[2 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 2 0]
 [0 0 0 0 5]], shape=(5, 5), dtype=int32)


## einsum()

In [8]:
tensor_einsum_2d_1 = tf.constant(np.random.randint(1, 4, (2, 2)))
tensor_einsum_2d_2 = tf.constant(np.random.randint(1, 4, (2, 2)))
tensor_einsum_3d_1 = tf.constant(np.random.randint(1, 4, (2, 2, 2)))
tensor_einsum_3d_2 = tf.constant(np.random.randint(1, 4, (2, 2, 2)))

print(tensor_einsum_2d_1)
print(tensor_einsum_2d_2)
print(tensor_einsum_3d_1)
print(tensor_einsum_3d_2)

tf.Tensor(
[[2 3]
 [1 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[[3 1]
  [1 1]]

 [[3 1]
  [1 3]]], shape=(2, 2, 2), dtype=int32)
tf.Tensor(
[[[3 3]
  [1 3]]

 [[3 1]
  [3 1]]], shape=(2, 2, 2), dtype=int32)


In [9]:
tensor_einsum_2d_matrix = tf.linalg.einsum(
    "ij,jk->ik",
    tensor_einsum_2d_1,
    tensor_einsum_2d_2,
)

tensor_einsum_2d_elementwise = tf.linalg.einsum(
    "ij,ij->ij",
    tensor_einsum_2d_1,
    tensor_einsum_2d_2,
)

print(tensor_einsum_2d_matrix)
print(tensor_einsum_2d_elementwise)

tf.Tensor(
[[5 5]
 [3 3]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 3]
 [1 2]], shape=(2, 2), dtype=int32)


In [10]:
tensor_einsum_3d_matrix = tf.linalg.einsum(
    "bij,bjk->bik",
    tensor_einsum_3d_1,
    tensor_einsum_3d_2,
)

tensor_einsum_3d_elementwise = tf.linalg.einsum(
    "bij,bij->bij",
    tensor_einsum_3d_1,
    tensor_einsum_3d_2,
)

print(tensor_einsum_3d_matrix)
print(tensor_einsum_3d_elementwise)

tf.Tensor(
[[[10 12]
  [ 4  6]]

 [[12  4]
  [12  4]]], shape=(2, 2, 2), dtype=int32)
tf.Tensor(
[[[9 3]
  [1 3]]

 [[9 1]
  [3 3]]], shape=(2, 2, 2), dtype=int32)


In [15]:
tensor_einsum_2d_sum = tf.linalg.einsum(
    "ij,ij->",
    tensor_einsum_2d_1,
    tensor_einsum_2d_2,
)

tensor_einsum_3d_sum = tf.linalg.einsum(
    "bij,bij->",
    tensor_einsum_3d_1,
    tensor_einsum_3d_2,
)

print(tensor_einsum_2d_sum)
print(tensor_einsum_3d_sum)

tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(32, shape=(), dtype=int32)
