# 5. Tensorflow Common Functions


In [2]:
import numpy as np
import tensorflow as tf

In [3]:
np.random.seed(42)
tf.random.set_seed(42)

In [4]:
tensor_1 = tf.constant(np.random.randint(1, 6, (2, 2, 3)), dtype=tf.dtypes.int32)
tensor_2 = tf.constant(np.random.randint(1, 6, (2, 3, 2)), dtype=tf.dtypes.int32)

print(tensor_1)
print(tensor_2)

tf.Tensor(
[[[4 5 3]
  [5 5 2]]

 [[3 3 3]
  [5 4 3]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[[5 2]
  [4 2]
  [4 5]]

 [[1 4]
  [2 5]
  [4 1]]], shape=(2, 3, 2), dtype=int32)


## expand_dims()


In [5]:
tensor_expand_dims0 = tf.expand_dims(tensor_1, axis=0)
tensor_expand_dims1 = tf.expand_dims(tensor_1, axis=1)
tensor_expand_dims2 = tf.expand_dims(tensor_1, axis=2)
tensor_expand_dims3 = tf.expand_dims(tensor_1, axis=3)

print(tensor_expand_dims0)
print(tensor_expand_dims1)
print(tensor_expand_dims2)
print(tensor_expand_dims3)

tf.Tensor(
[[[[4 5 3]
   [5 5 2]]

  [[3 3 3]
   [5 4 3]]]], shape=(1, 2, 2, 3), dtype=int32)
tf.Tensor(
[[[[4 5 3]
   [5 5 2]]]


 [[[3 3 3]
   [5 4 3]]]], shape=(2, 1, 2, 3), dtype=int32)
tf.Tensor(
[[[[4 5 3]]

  [[5 5 2]]]


 [[[3 3 3]]

  [[5 4 3]]]], shape=(2, 2, 1, 3), dtype=int32)
tf.Tensor(
[[[[4]
   [5]
   [3]]

  [[5]
   [5]
   [2]]]


 [[[3]
   [3]
   [3]]

  [[5]
   [4]
   [3]]]], shape=(2, 2, 3, 1), dtype=int32)


## squeeze()


In [6]:
tensor_squeeze_dims1 = tf.squeeze(tensor_expand_dims1)

print(tensor_squeeze_dims1)

tf.Tensor(
[[[4 5 3]
  [5 5 2]]

 [[3 3 3]
  [5 4 3]]], shape=(2, 2, 3), dtype=int32)


## reshape()


In [7]:
tensor_reshape = tf.reshape(tensor_1, shape=(2, 6))

print(tensor_reshape)

tf.Tensor(
[[4 5 3 5 5 2]
 [3 3 3 5 4 3]], shape=(2, 6), dtype=int32)


## concat()


In [8]:
tensor_concat0 = tf.concat([tensor_1, tf.transpose(tensor_2, perm=(0, 2, 1))], axis=0)
tensor_concat1 = tf.concat([tensor_1, tf.transpose(tensor_2, perm=(0, 2, 1))], axis=1)
tensor_concat2 = tf.concat([tensor_1, tf.transpose(tensor_2, perm=(0, 2, 1))], axis=2)

print(tensor_concat0)
print(tensor_concat1)
print(tensor_concat2)

tf.Tensor(
[[[4 5 3]
  [5 5 2]]

 [[3 3 3]
  [5 4 3]]

 [[5 4 4]
  [2 2 5]]

 [[1 2 4]
  [4 5 1]]], shape=(4, 2, 3), dtype=int32)
tf.Tensor(
[[[4 5 3]
  [5 5 2]
  [5 4 4]
  [2 2 5]]

 [[3 3 3]
  [5 4 3]
  [1 2 4]
  [4 5 1]]], shape=(2, 4, 3), dtype=int32)
tf.Tensor(
[[[4 5 3 5 4 4]
  [5 5 2 2 2 5]]

 [[3 3 3 1 2 4]
  [5 4 3 4 5 1]]], shape=(2, 2, 6), dtype=int32)


## stack()


In [10]:
tensor_stack_0 = tf.stack([tensor_1, tf.transpose(tensor_2, perm=(0, 2, 1))], axis=0)
tensor_stack_1 = tf.stack([tensor_1, tf.transpose(tensor_2, perm=(0, 2, 1))], axis=1)
tensor_stack_2 = tf.stack([tensor_1, tf.transpose(tensor_2, perm=(0, 2, 1))], axis=2)

print(tensor_stack_0)
print(tensor_stack_1)
print(tensor_stack_2)

tf.Tensor(
[[[[4 5 3]
   [5 5 2]]

  [[3 3 3]
   [5 4 3]]]


 [[[5 4 4]
   [2 2 5]]

  [[1 2 4]
   [4 5 1]]]], shape=(2, 2, 2, 3), dtype=int32)
tf.Tensor(
[[[[4 5 3]
   [5 5 2]]

  [[5 4 4]
   [2 2 5]]]


 [[[3 3 3]
   [5 4 3]]

  [[1 2 4]
   [4 5 1]]]], shape=(2, 2, 2, 3), dtype=int32)
tf.Tensor(
[[[[4 5 3]
   [5 4 4]]

  [[5 5 2]
   [2 2 5]]]


 [[[3 3 3]
   [1 2 4]]

  [[5 4 3]
   [4 5 1]]]], shape=(2, 2, 2, 3), dtype=int32)


## pad()

In [33]:
t1 = tf.constant(np.random.randint(1, 6, (2, 3)), dtype=tf.dtypes.int32)
t2 = tf.constant(np.random.randint(1, 6, (2, 3)), dtype=tf.dtypes.int32)

print(t1)
print(t2)

t_pad_constant = tf.pad(t1, [[1, 1], [2, 2]], constant_values=99, mode="CONSTANT")
t_pad_reflect = tf.pad(t1, [[1, 1], [2, 2]], mode="REFLECT")
t_pad_symmetric = tf.pad(t1, [[1, 1], [2, 2]], mode="SYMMETRIC")

print(t_pad_constant)
print(t_pad_reflect)
print(t_pad_symmetric)

tf.Tensor(
[[2 2 2]
 [3 5 1]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[4 1 4]
 [1 5 4]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[99 99 99 99 99 99 99]
 [99 99  2  2  2 99 99]
 [99 99  3  5  1 99 99]
 [99 99 99 99 99 99 99]], shape=(4, 7), dtype=int32)
tf.Tensor(
[[1 5 3 5 1 5 3]
 [2 2 2 2 2 2 2]
 [1 5 3 5 1 5 3]
 [2 2 2 2 2 2 2]], shape=(4, 7), dtype=int32)
tf.Tensor(
[[2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [5 3 3 5 1 1 5]
 [5 3 3 5 1 1 5]], shape=(4, 7), dtype=int32)


## gather()

In [38]:
t1 = tf.constant(np.random.randint(1, 6, (5, 5)), dtype=tf.dtypes.int32)

print(t1)

t_gather_0d = tf.gather(t1, [2, 4], axis=0)
t_gather_1d = tf.gather(t1, [2, 4], axis=1)

print(t_gather_0d)
print(t_gather_1d)

tf.Tensor(
[[3 1 2 5 2]
 [2 1 4 2 3]
 [4 5 1 5 4]
 [4 4 5 4 5]
 [4 3 4 5 2]], shape=(5, 5), dtype=int32)
tf.Tensor(
[[4 5 1 5 4]
 [4 3 4 5 2]], shape=(2, 5), dtype=int32)
tf.Tensor(
[[2 2]
 [4 3]
 [1 4]
 [5 5]
 [4 2]], shape=(5, 2), dtype=int32)


## gather_nd()

In [49]:
t = tf.constant(np.random.randint(1, 6, (2, 3, 4)), dtype=tf.dtypes.int32)

print(t)

t_gather_nd_batch0 = tf.gather_nd(t, [[0, 1], [1, 2]], batch_dims=0)
t_gather_nd_batch1 = tf.gather_nd(t, [[0, 1], [1, 2]], batch_dims=1)

print(t_gather_nd_batch0)
print(t_gather_nd_batch1)

tf.Tensor(
[[[1 5 3 1]
  [3 4 2 4]
  [4 5 2 4]]

 [[4 2 2 4]
  [2 4 4 5]
  [1 4 3 1]]], shape=(2, 3, 4), dtype=int32)
tf.Tensor(
[[3 4 2 4]
 [1 4 3 1]], shape=(2, 4), dtype=int32)
tf.Tensor([5 4], shape=(2,), dtype=int32)
