# 6. Ragged Tensors

In [22]:
import numpy as np

import tensorflow as tf

In [23]:
np.random.seed(42)
tf.random.set_seed(42)

## constant()

In [24]:
tensor = tf.ragged.constant(
    [
        np.random.randint(1, 6, (4)),
        np.random.randint(1, 6, (2)),
        np.random.randint(1, 6, (3)),
        np.random.randint(1, 6, (1)),
    ]
)

print(tensor)

<tf.RaggedTensor [[4, 5, 3, 5], [5, 2], [3, 3, 3], [5]]>


## boolean_mask()

In [25]:
tensor = tf.ragged.constant(
    [
        [2, 1, 4, 3],
        [1, 2],
        [1, 4, 1],
        [3],
    ]
)

print(tensor)

mask0 = tf.ragged.constant(
    [
        [True, False, True, False],
        [True, True],
        [False, True, True],
        [True],
    ]
)

mask1 = tf.ragged.constant([True, False, False, True])

output0 = tf.ragged.boolean_mask(tensor, mask0)
output1 = tf.ragged.boolean_mask(tensor, mask1)

print(output0)
print(output1)

<tf.RaggedTensor [[2, 1, 4, 3], [1, 2], [1, 4, 1], [3]]>
<tf.RaggedTensor [[2, 4], [1, 2], [4, 1], [3]]>
<tf.RaggedTensor [[2, 1, 4, 3], [3]]>


## RaggedTensor.from_row_lengths()

In [26]:
tensor = tf.constant(np.random.randint(0, 10, 16))

print(tensor)

row_lengths = tf.constant([3, 4, 1, 0, 4, 2, 0, 1, 0, 1])

output = tf.RaggedTensor.from_row_lengths(values=tensor, row_lengths=row_lengths)

print(output)

tf.Tensor([3 7 7 2 5 4 1 7 5 1 4 0 9 5 8 0], shape=(16,), dtype=int32)
<tf.RaggedTensor [[3, 7, 7], [2, 5, 4, 1], [7], [], [5, 1, 4, 0], [9, 5], [], [8], [], [0]]>


## RaggedTensor.from_row_limits()

In [27]:
tensor = tf.constant(np.random.randint(0, 10, 16))

print(tensor)

row_limits = tf.constant([4, 4, 7, 9, 13, 14, 14, 14, 16])

output = tf.RaggedTensor.from_row_limits(values=tensor, row_limits=row_limits)

print(output)

tf.Tensor([9 2 6 3 8 2 4 2 6 4 8 6 1 3 8 1], shape=(16,), dtype=int32)
<tf.RaggedTensor [[9, 2, 6, 3], [], [8, 2, 4], [2, 6], [4, 8, 6, 1], [3], [], [], [8, 1]]>


## RaggedTensor.from_row_splits()

In [28]:
tensor = tf.constant(np.random.randint(0, 10, 16))

print(tensor)

row_splits = tf.constant([0, 4, 7, 9, 13, 14, 14, 14, 16])

output = tf.RaggedTensor.from_row_splits(values=tensor, row_splits=row_splits)

print(output)

tf.Tensor([9 8 9 4 1 3 6 7 2 0 3 1 7 3 1 5], shape=(16,), dtype=int32)
<tf.RaggedTensor [[9, 8, 9, 4], [1, 3, 6], [7, 2], [0, 3, 1, 7], [3], [], [], [1, 5]]>
