# 7. Sparse Tensors

In [2]:
import numpy as np

import tensorflow as tf

In [ ]:
np.random.seed(42)
tf.random.set_seed(42)

In [10]:
values = np.random.randint(0, 9, 5)

print(values)

indices = [[1, 1], [2, 3], [3, 0], [3, 3], [4, 2]]

dense_shape = [5, 5]

tensor = tf.SparseTensor(indices, values, dense_shape)

print(tf.sparse.to_dense(tensor))

[1 7 3 5 8]
tf.Tensor(
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 7 0]
 [3 0 0 5 0]
 [0 0 8 0 0]], shape=(5, 5), dtype=int32)
