# String Tensors

In [1]:
import numpy as np

import tensorflow as tf

In [2]:
np.random.seed(42)
tf.random.set_seed(42)

In [3]:
tensor = tf.constant(["Hello", "World"])

print(tensor)

tf.Tensor([b'Hello' b'World'], shape=(2,), dtype=string)
tf.Tensor(b'Hello World', shape=(), dtype=string)


## join()

In [ ]:
tensor_join = tf.strings.join(tensor, " ")

print(tensor_join)

## lower() / upper

In [5]:
tensor_lower = tf.strings.lower(tensor)
tensor_upper = tf.strings.upper(tensor)

print(tensor_lower)
print(tensor_upper)

tf.Tensor([b'hello' b'world'], shape=(2,), dtype=string)
tf.Tensor([b'HELLO' b'WORLD'], shape=(2,), dtype=string)
